name: Tweets diarios de eventos

on:
  schedule:
    - cron: '0 7 * * *'   # 07:00 UTC ≈ 09:00 Europe/Madrid
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm init -y
      - run: npm install rss-parser twitter-api-v2
      - name: Publicar tuits de los eventos de hoy
        run: node scripts/post-x.js
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
